### ISSUE TITLE
Submenu Widget

### ISSUE THREAD

**Issue by Satris404** [jurialmunkey/skin.fuse.neue#2]
Most of submenu's widget don't work. They show up as empty. (Music files, actors, addons, etc)

**Comment by jurialmunkey** [comment]
Please download the github version of skinshortcuts. There has been a long standing bug in skinshortcuts which was fixed quite a while ago, but it appears it was never pushed to the official repo:
https://github.com/BigNoid/script.skinshortcuts

**Comment by Satris404** [comment]
Thanks! Everything works fine now.
